### ISSUE TITLE
Problem s afrikatima

### ISSUE THREAD

**Issue by EzicJ** [malcodeman/resumebuilder.dev#42]
Pozdrav,
super projekat, svaka čast na ovome što si napravio, definitivno od sad koristim za svoj CV.

Primjetio sam problem, ali nisam siguran jel do mog configa (Win10, Brave Browser) ili do stranice.
Kad hoću da exportam CV ko html pojave se simboli umjesto ć u prezimenu.

![image](https://user-images.githubusercontent.com/58070077/205049104-80f69bb6-e237-4ccf-ab30-157fd87a86ec.png)

Hvala!

**Comment by malcodeman** [comment]
Pozdrav,

Testirao sam Nairobi template HTML export sa svojim cv i primijetio sam isti problem na Brave browseru. 
Na Chrome karakter ć se prikaze OK tako da trenutno nisam siguran u cemu je problem obzirom da je i Brave baziran na Chromium. Kreiram todo ticket za ovaj problem, hvala na prijavljivanju.
